import type { Metadata } from 'next'
import { Mulish } from 'next/font/google'
import { ChildProps } from '@/types'
import './globals.css'
import TopLoader from '@/components/shared/top-loader'
import { Toaster } from 'sonner'

const mulish = Mulish({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000'],
  variable: '--font-mulish',
})

export const metadata: Metadata = {
  title: 'ArxPro',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<ChildProps>) {
  return (
    <html lang='en'>
      <body className={`${mulish.variable} antialiased custom-scrollbar`}>
        <TopLoader />
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  )
}
